#ifndef TEST_FRAMEWORK_TYPES_UTILS_H
#define TEST_FRAMEWORK_TYPES_UTILS_H
typedef enum direction {ASCENDING = 1, DESCENDING = 2} dir;
typedef enum algorithm {BUBBLE_SORT = 1, SELECTION_SORT = 2, INSERTION_SORT = 3} alg;
#endif //TEST_FRAMEWORK_TYPES_UTILS_H
